[package]
name = "synth-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
synth-dsp     = { path = "../synth-dsp" }
synth-common  = { path = "../synth-common" }
synth-control = { path = "../synth-control" }
fundsp        = { version = "0.23", features = ["files", "fft"] }
serde         = { version = "1", features = ["derive"] }

[dev-dependencies]
synth-control = { path = "../synth-control", features = ["serde"] }
serde_json    = "1"
