[package]
name = "ambient-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
synth-common  = { path = "../synth-common" }
synth-engine  = { path = "../synth-engine" }
synth-control = { path = "../synth-control" }
fundsp        = { version = "0.23", features = ["files", "fft"] }
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"
anyhow        = "1"
